apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: api-success-rate
  namespace: demo
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 3
      failureLimit: 1
      successCondition: result[0] >= 0.95
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(flask_http_request_total{namespace="demo",service="api",status!~"5.."}[2m]))
            /
            clamp_min(sum(rate(flask_http_request_total{namespace="demo",service="api"}[2m])), 0.001)