apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-slo-rules
  namespace: demo
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: api-slo
      rules:
        - alert: ApiHighErrorRate
          expr: |
            (
              sum(rate(flask_http_request_total{namespace="demo",service="api",status=~"5.."}[5m]))
              /
              clamp_min(sum(rate(flask_http_request_total{namespace="demo",service="api"}[5m])), 0.001)
            ) > 0.05
          for: 5m
          labels:
            severity: warning
            service: api
            slo: api-success-rate
          annotations:
            summary: "API error rate is above 5%"
            description: "API service in namespace demo has more than 5% HTTP 5xx responses for 5 minutes. Current error ratio: {{ $value | humanizePercentage }}."
            runbook_url: "https://github.com/truongcongtu318/gitops_lab"
        - alert: ApiCriticalErrorRate
          expr: |
            (
              sum(rate(flask_http_request_total{namespace="demo",service="api",status=~"5.."}[5m]))
              /
              clamp_min(sum(rate(flask_http_request_total{namespace="demo",service="api"}[5m])), 0.001)
            ) > 0.20
          for: 2m
          labels:
            severity: critical
            service: api
            slo: api-success-rate
          annotations:
            summary: "API critical error rate is above 20%"
            description: "API service in namespace demo has more than 20% HTTP 5xx responses for 2 minutes. Current error ratio: {{ $value | humanizePercentage }}."
            runbook_url: "https://github.com/truongcongtu318/gitops_lab"
        - alert: ApiTargetDown
          expr: up{namespace="demo",service="api"} == 0
          for: 2m
          labels:
            severity: critical
            service: api
            slo: api-availability
          annotations:
            summary: "API target is down"
            description: "Prometheus cannot scrape the API target in namespace demo for more than 2 minutes. Check pod status, ServiceMonitor, service endpoints, and /metrics endpoint."
            runbook_url: "https://github.com/truongcongtu318/gitops_lab"
        - alert: ApiCanaryRolloutFailed
          expr: |
            rollout_phase{namespace="demo",name="api",phase="Abort"} == 1
          for: 0m
          labels:
            severity: critical
            service: api
            slo: api-canary
          annotations:
            summary: "API canary rollout failed"
            description: "Rollout {{ $labels.namespace }}/{{ $labels.name }} is in Abort phase. Argo Rollouts aborted the canary after analysis failed."
            runbook_url: "https://github.com/truongcongtu318/gitops_lab"
