apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
        alertmanager:
          alertmanagerSpec:
            secrets:
              - alertmanager-smtp-password
          config:
            global:
              smtp_smarthost: smtp.gmail.com:587
              smtp_from: tutc.work@gmail.com
              smtp_auth_username: tutc.work@gmail.com
              smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-smtp-password/password
              smtp_require_tls: true
            route:
              receiver: email-personal
              group_by: ['alertname', 'namespace', 'service']
              group_wait: 10s
              group_interval: 1m
              repeat_interval: 30m
            receivers:
              - name: email-personal
                email_configs:
                  - to: tutc.work@gmail.com
                    send_resolved: true
        grafana:
          adminPassword: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true