apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
        alertmanager:
          alertmanagerSpec:
            secrets:
              - alertmanager-smtp-password
          config:
            global:
              resolve_timeout: 5m
              smtp_smarthost: smtp.gmail.com:587
              smtp_from: tutc.work@gmail.com
              smtp_auth_username: tutc.work@gmail.com
              smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-smtp-password/password
              smtp_require_tls: true
            route:
              receiver: "null"
              group_by: ['alertname', 'namespace', 'service', 'severity']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 4h
              routes:
                - receiver: email-api-alerts
                  matchers:
                    - service = "api"
                    - severity =~ "warning|critical"
                  group_wait: 30s
                  group_interval: 5m
                  repeat_interval: 4h
            inhibit_rules:
              - source_matchers:
                  - severity = "critical"
                target_matchers:
                  - severity = "warning"
                equal: ['namespace', 'service', 'slo']
            receivers:
              - name: "null"
              - name: email-api-alerts
                email_configs:
                  - to: tutc.work@gmail.com
                    send_resolved: true
                    headers:
                      subject: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} {{ .CommonLabels.namespace }}/{{ .CommonLabels.service }}'
        grafana:
          adminPassword: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true